### ISSUE TITLE
Use environment variables

### ISSUE THREAD

**Issue by rap2hpoutre** [prisma/vscode-graphql#124]
Thank you for this plugin.

Is there a way to set then access env variables? Let's say I need to connect to github API, I don't want to write my github token in `.graphqlconfig.yml`. Is there a way to set then use env vars?

**Comment by divyenduz** [comment]
Thanks for raising this issue :) 

Yes, it is possible and documented here: https://github.com/prisma/graphql-config/blob/master/specification.md#referencing-environment-variables

It is a part of the GraphQL config project. 

Please feel free to raise a PR if you think that this information belongs to the README of this project as well? 

If your issue is resolved, please close the issue, thanks.

**Comment by rap2hpoutre** [comment]
Thank you for your answer @divyenduz. It solved my problem! I don't think it has to be in the readme, so it's OK I close this issue!
